<a href="https://colab.research.google.com/github/Himani0/Breast_Cancer_Prediction/blob/main/Breast_cancer_prediction_using_KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Breast Cancer Prediction **using KNN**

In [2]:
import numpy as np
import sklearn.datasets

In [3]:
breast_cancer = sklearn.datasets.load_breast_cancer()

In [5]:
print(breast_cancer)

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]]), 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
 

In [6]:
X = breast_cancer.data

In [7]:
Y = breast_cancer.target

In [8]:
X

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [11]:
print(X.shape)

(569, 30)


In [12]:
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [13]:
print(Y.shape)

(569,)


In [14]:
import pandas as pd

In [15]:
data = pd.DataFrame(breast_cancer.data, columns=breast_cancer.feature_names)

In [16]:
data

mean radius  mean texture  ...  worst symmetry  worst fractal dimension
0          17.99         10.38  ...          0.4601                  0.11890
1          20.57         17.77  ...          0.2750                  0.08902
2          19.69         21.25  ...          0.3613                  0.08758
3          11.42         20.38  ...          0.6638                  0.17300
4          20.29         14.34  ...          0.2364                  0.07678
..           ...           ...  ...             ...                      ...
564        21.56         22.39  ...          0.2060                  0.07115
565        20.13         28.25  ...          0.2572                  0.06637
566        16.60         28.08  ...          0.2218                  0.07820
567        20.60         29.33  ...          0.4087                  0.12400
568         7.76         24.54  ...          0.2871                  0.07039

[569 rows x 30 columns]

In [18]:
data['class'] = breast_cancer.target

In [26]:
data.head()

mean radius  mean texture  ...  worst fractal dimension  class
0        17.99         10.38  ...                  0.11890      0
1        20.57         17.77  ...                  0.08902      0
2        19.69         21.25  ...                  0.08758      0
3        11.42         20.38  ...                  0.17300      0
4        20.29         14.34  ...                  0.07678      0

[5 rows x 31 columns]

In [30]:
print(data['class'].value_counts())

1    357
0    212
Name: class, dtype: int64


In [31]:
print(breast_cancer.target_names)

['malignant' 'benign']


In [32]:
data.groupby(['class']).mean()

mean radius  mean texture  ...  worst symmetry  worst fractal dimension
class                             ...                                         
0        17.462830     21.604906  ...        0.323468                 0.091530
1        12.146524     17.914762  ...        0.270246                 0.079442

[2 rows x 30 columns]

In [33]:
from sklearn.model_selection import train_test_split

In [34]:
X_train , X_test , Y_train , Y_test = train_test_split(X,Y)

In [36]:
print(X_train , X_train.shape , X_test , X_test.shape)

[[1.194e+01 2.076e+01 7.787e+01 ... 1.155e-01 2.465e-01 9.981e-02]
 [1.377e+01 1.327e+01 8.806e+01 ... 5.802e-02 2.823e-01 6.794e-02]
 [1.614e+01 1.486e+01 1.043e+02 ... 1.129e-01 2.778e-01 7.012e-02]
 ...
 [1.239e+01 1.748e+01 8.064e+01 ... 9.804e-02 2.819e-01 1.118e-01]
 [1.468e+01 2.013e+01 9.474e+01 ... 1.609e-01 3.029e-01 8.216e-02]
 [1.510e+01 1.639e+01 9.958e+01 ... 1.423e-01 2.590e-01 7.779e-02]] (426, 30) [[1.167e+01 2.002e+01 7.521e+01 ... 8.120e-02 3.206e-01 8.950e-02]
 [1.189e+01 1.835e+01 7.732e+01 ... 1.138e-01 3.397e-01 8.365e-02]
 [1.362e+01 2.323e+01 8.719e+01 ... 7.174e-02 2.642e-01 6.953e-02]
 ...
 [1.025e+01 1.618e+01 6.652e+01 ... 9.744e-02 2.608e-01 9.702e-02]
 [1.566e+01 2.320e+01 1.102e+02 ... 2.462e-01 3.277e-01 1.019e-01]
 [1.746e+01 3.928e+01 1.134e+02 ... 2.066e-01 2.853e-01 8.496e-02]] (143, 30)


In [37]:
print(Y_train , Y_train.shape , Y_test , Y_test.shape)

[1 1 1 0 0 0 0 0 0 1 0 0 1 1 1 1 1 1 0 1 1 0 1 1 1 1 0 1 1 1 1 1 0 0 0 0 1
 0 1 1 1 0 1 0 1 1 1 1 1 1 0 1 0 0 1 0 1 0 0 0 0 1 1 1 0 0 1 0 0 1 1 0 0 1
 0 1 1 1 0 1 1 0 1 1 1 1 1 0 1 1 1 1 1 1 1 0 1 0 1 1 0 0 1 0 1 0 0 0 0 1 1
 0 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 0 1 0 1 1 1 1 0 1 1 0 0 0 1 0 0 0 0
 0 1 1 0 1 1 0 1 1 0 1 1 0 1 1 1 1 1 0 0 1 1 1 1 1 0 1 1 1 0 1 0 1 1 0 0 0
 1 0 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 0 0 1 1 0 1 0 1 1 1 1 0 0 1 0 1 0
 0 1 1 1 1 0 0 0 0 0 1 1 0 1 1 1 1 1 0 0 0 1 1 1 1 1 0 0 1 0 1 0 0 1 1 1 0
 1 1 1 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 0 1 1 1 0 0 1 0 1 0 0 1 1 1 0 0 1 0 0
 0 1 0 1 1 0 0 0 1 0 1 1 0 1 0 1 1 1 1 1 0 0 1 0 0 0 0 1 1 0 1 1 1 1 1 1 1
 0 0 0 1 1 1 1 1 0 0 1 1 1 0 1 0 0 0 0 0 1 1 0 1 1 0 1 1 1 0 1 1 1 1 1 1 0
 1 1 0 0 0 1 1 1 1 0 0 1 1 0 0 1 1 0 1 0 0 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 1
 0 1 1 1 1 0 0 0 0 0 1 0 1 1 1 1 1 0 1] (426,) [1 1 1 1 0 1 1 0 0 1 1 0 0 0 1 1 0 0 1 1 1 1 1 0 1 1 1 1 1 0 1 0 1 1 1 0 1
 0 1 1 1 1 0 1 1 0 0 1 0 1 1 0 0 0 1 1 1 1 1 1 1 1 1 

In [38]:
print(Y.shape , Y_train.shape , Y_test.shape)

(569,) (426,) (143,)


In [39]:
X_train , X_test , Y_train , Y_test = train_test_split(X,Y,test_size=0.1)

In [40]:
print(Y.shape , Y_train.shape , Y_test.shape)

(569,) (512,) (57,)


In [41]:
print(Y.mean() , Y_train.mean() , Y_test.mean())

0.6274165202108963 0.619140625 0.7017543859649122


In [43]:
X_train , X_test , Y_train , Y_test = train_test_split(X,Y,test_size=0.1,stratify=Y)

In [46]:
print(X.shape , X_train.shape , X_test.shape , X.mean() , X_train.mean() , X_test.mean())

(569, 30) (512, 30) (57, 30) 61.890712339519624 61.412447526145826 66.1867050491228


In [47]:
print(Y.shape , Y_train.shape , Y_test.shape , Y.mean() , Y_train.mean() , Y_test.mean())

(569,) (512,) (57,) 0.6274165202108963 0.626953125 0.631578947368421


In [48]:
X_train , X_test , Y_train , Y_test = train_test_split(X,Y,test_size=0.1,stratify=Y,random_state=1)

In [49]:
from sklearn.neighbors import KNeighborsClassifier

In [53]:
neigh = KNeighborsClassifier(n_neighbors=6)

In [54]:
neigh.fit(X_train , Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=6, p=2,
                     weights='uniform')

In [55]:
from sklearn.metrics import accuracy_score

In [56]:
prediction_on_training_data = neigh.predict(X_train)

accuracy_on_training_data = accuracy_score(Y_train , prediction_on_training_data)

In [57]:
print("Accuracy on Training data is:", accuracy_on_training_data)

Accuracy on Training data is: 0.943359375


In [58]:
prediction_on_testing_data = neigh.predict(X_test)

accuracy_on_testing_data = accuracy_score(Y_test , prediction_on_testing_data)

In [59]:
print("Accuracy on testing data is:", accuracy_on_testing_data)

Accuracy on testing data is: 0.9298245614035088


In [60]:
input_data = (12.45,15.7,82.57,477.1,0.1278,0.17,0.1578,0.08089,0.2087,0.07613,0.3345,0.8902,2.217,27.19,0.00751,0.03345,0.03672,0.01137,0.02165,0.005082,15.47,23.75,103.4,741.6,0.1791,0.5249,0.5355,0.1741,0.3985,0.1244)

In [61]:
input_data_as_np_array = np.asarray(input_data)

In [65]:
data_reshaped = input_data_as_np_array.reshape(1,-1)

In [66]:
data_reshaped

array([[1.245e+01, 1.570e+01, 8.257e+01, 4.771e+02, 1.278e-01, 1.700e-01,
        1.578e-01, 8.089e-02, 2.087e-01, 7.613e-02, 3.345e-01, 8.902e-01,
        2.217e+00, 2.719e+01, 7.510e-03, 3.345e-02, 3.672e-02, 1.137e-02,
        2.165e-02, 5.082e-03, 1.547e+01, 2.375e+01, 1.034e+02, 7.416e+02,
        1.791e-01, 5.249e-01, 5.355e-01, 1.741e-01, 3.985e-01, 1.244e-01]])

In [67]:
prediction = neigh.predict(data_reshaped)
print(prediction)

[0]


In [68]:
if prediction[0] == 0:
  print("Breast Cancer is Malignant")
else:
  print("Breast Cancer is Benign")

Breast Cancer is Malignant


In [69]:
another_data = (9.504,12.44,60.34,273.9,0.1024,0.06492,0.02956,0.02076,0.1815,0.06905,0.2773,0.9768,1.909,15.7,0.009606,0.01432,0.01985,0.01421,0.02027,0.002968,10.23,15.66,65.13,314.9,0.1324,0.1148,0.08867,0.06227,0.245,0.07773)

In [70]:
as_numpy_array = np.asarray(another_data)

In [71]:
reshaped_data = as_numpy_array.reshape(1,-3)

In [72]:
lets_predict = neigh.predict(reshaped_data)
print(lets_predict)

[1]


In [73]:
if lets_predict[0] == 0:
  print("Breast Cancer is Malignant")
else:
  print("Breast Cancer is Benign")

Breast Cancer is Benign
